name: Buzzy flow

on:
    repository_dispatch:
          types: [Buzzy]

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:     
     - name : upload files
  #     if: github.event.action == 'Buzzy'
       uses: actions/checkout@v2
       with:
        ref: ${{ github.event.client_payload.branch || 'deploy' }}
        persist-credentials: false
        fetch-depth: 0
     - run:
          | 
            mkdir -p sanj2
            mv sanj/sanjtest.txt sanj2/buzzy.txt  
            ls 
            pwd
     - uses: zdurham/s3-upload-github-action@master
       env:
         #FILE: /home/runner/windowsbuild/sanjtest2.txt
         FILE: sanj2/buzzy.txt 
         AWS_REGION: 'ap-southeast-2'
         S3_BUCKET: 'sj-flowtest'
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
         
     - name: Commit changes
       run: |
            git config --global user.name 'buzzydevops'
            git config --global user.email 'devops@buzzy.buzz'
            git commit -am "Android version bump by CI"
            git push origin deploy

     - name: Push changes
       uses: ad-m/github-push-action@master
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}         
         
     - name: SendGrid
       uses: peter-evans/sendgrid-action@v1
       env:
         SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
         SCRIPT_FILEPATH: ./.github/scripts/sendgrid.js
