name: Flow1

on:
  push:
    branches: [ workflow_test ]
    paths:
      - '**'
      - '!.github/workflows/**'
jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Upload file to bucket
        uses: koraykoska/s3-upload-github-action@master
        env:
          FILE: sanj
          S3_BUCKET: sj-flowtest
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
