name: mongo dump

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Selected Branch should be'
        required: true
        default: 'master'


jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [4.0, 4.2, 4.4]
    steps:     
     - name : Git checkout 
       uses: actions/checkout@v2
  #     with:
  #      ref: ${{ github.event.client_payload.branch || 'Master' }}
     - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.3.0
       with:
          mongodb-version: ${{ matrix.mongodb-version }} 
      
     - run:
          | 
            mkdir -p mongodump
            cd mongodump
            mongodump --uri="mongodb+srv://buzzyuser:OH70GAX9TJCMNijk@cluster0-bvmnd.mongodb.net/buzzyapp?retryWrites=true&w=majority"

