name: mongo connect test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Selected Branch should be'
        required: true
        default: 'master'



jobs:
  test_mongo_action:
    runs-on: ubuntu-latest
    name: Test mongo-action
    steps:
      - name: install mongo shell
        run: 
             |
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
              echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.lis
              sudo apt-get update
              sudo apt-get install -y mongodb-org-shell

      - name: Test mongo connection
        run:  sudo mongo "mongodb+srv://buzzytest.yvjew.azure.mongodb.net
