name: mongo connect test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Selected Branch should be'
        required: true
        default: 'master'



jobs:
  test_mongo_action:
    runs-on: ubuntu-latest
    name: Test mongo-action
    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: Test mongo connection
        id: test_mongo_connection
        run: "sudo mongo 'mongodb+srv://buzzyapp2:DJ70GAX9TJCMNijk@cluster0.dlopt.mongodb.net/buzzy?retryWrites=true&w=majority'"

