name: mongo dump

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Selected Branch should be'
        required: true
        default: 'master'


jobs:

  build:
    runs-on: ubuntu-latest
   
    steps:     
     - name : Git checkout 
       uses: actions/checkout@v2
  #     with:
  #      ref: ${{ github.event.client_payload.branch || 'Master' }}
     - name: Start MongoDB
       uses: supercharge/mongodb-github-action@1.3.0
             
     - run:
          | 
            mkdir -p mongodump
            cd mongodump
            mongodump --uri = "mongodb+srv://buzzyapp2:DJ70GAX9TJCMNijk@cluster0.dlopt.mongodb.net/buzzy?retryWrites=true&w=majority"

