name: Server Version Up

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The branch selected above should be'
        required: true
        default: 'buzzy-production'

jobs:
  build:
    runs-on: [ubuntu-latest]
    timeout-minutes: 15
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
      with:
        token: ${{secrets.PAT}}
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7 #install python 
    - name: execute py script # run the run.py to update version 
      run: |
        python ./.github/scripts/versionup.py
    
    #- name: Commit version bump      
    #  run: |
    #      git config --global user.name 'Sanj Edirisinghe'
    #      git config --global user.email 'sanj.ediringhe@buzzy.buzz'
    #      git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/$GITHUB_REPOSITORY
    #      git checkout "${GITHUB_REF:11}"
    #      git commit -am "Version Bump"
    #      git push
    - name: Commit changes # commit changes to version file
      uses: EndBug/add-and-commit@v5
      with:
        author_name: Sanj
        author_email: sanj.edirisinghe@buzzy.buzz
        message: "Bump up version by CI"
        add: "private/version.json"
      env:
        TOKEN: ${{ secrets.PAT }}   
